# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint and test
      run: |
        npm run lint
        npm test -- --watch=false
      env:
        CI: true
  
  e2e:
    runs-on: [ubuntu-latest]
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run e2e tests
      run: npm run e2e
      env:
        CI: true
